### ISSUE TITLE
Uncaught TypeError: this.element.querySelector is not a function

### ISSUE THREAD

**Issue by juliancruzsanchez** [xtoolkit/arshen-ac#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [arshen-ac](https://github.com/xtoolkit/arshen-ac) package 0.9.5

### Stack Trace

Uncaught TypeError: this.element.querySelector is not a function

```
At C:\Users\Julian Sanchez\.atom\packages\arshen-ac\node_modules\atom-package-deps\lib\view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/packages/arshen-ac/node_modules/atom-package-deps/lib/view.js:41:36)
    at /packages/arshen-ac/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/packages/arshen-ac/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
  2x -1:35.5.0 core:move-down (input.hidden-input)
     -1:34.5.0 snippets:previous-tab-stop (input.hidden-input)
     -1:34.5.0 editor:outdent-selected-rows (input.hidden-input)
  2x -1:33 core:move-down (input.hidden-input)
  3x -1:31.9.0 core:move-up (input.hidden-input)
 40x -1:30.9.0 core:move-down (input.hidden-input)
     -0:51.8.0 core:select-all (input.hidden-input)
  2x -0:49.8.0 core:save (ul.list-inline.tab-bar.inset-panel)
     -0:41.7.0 editor:newline (input.hidden-input)
     -0:41.2.0 core:move-up (input.hidden-input)
  2x -0:34.5.0 core:backspace (input.hidden-input)
 15x -0:31.2.0 core:move-left (input.hidden-input)
 16x -0:29.2.0 core:move-right (input.hidden-input)
     -0:25.9.0 core:move-left (input.hidden-input)
  2x -0:01.4.0 core:backspace (input.hidden-input)
     -0:00.6.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
arshen-ac 0.9.5 
atom-beautify 0.30.3 
atom-json-color 0.6.0 
file-icons 2.1.8 
fuse 0.4.0 
fuse-snippets 0.2.0 
git-plus 7.9.3 
highlight-selected 0.13.1 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
piatto-light-syntax 0.2.2 
pigments 0.39.1 
pristine-ui 1.0.15 
pure-syntax 0.2.1 
Remote-FTP 1.1.2 
tool-bar 1.1.0 
```

**Comment by xtoolkit** [comment]
i release a update
please check
sry 4 bad english
