### ISSUE TITLE
Having problems 

### ISSUE THREAD

**Issue by ghost** [xtoolkit/arshen-ac#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [arshen-ac](https://github.com/xtoolkit/arshen-ac) package 0.9.6

### Stack Trace

Uncaught TypeError: this.element.querySelector is not a function

```
At C:\Users\wdarn\.atom\packages\arshen-ac\node_modules\atom-package-deps\lib\view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/packages/arshen-ac/node_modules/atom-package-deps/lib/view.js:41:36)
    at /packages/arshen-ac/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/packages/arshen-ac/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.e.on.e (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1126857)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
```

### Non-Core Packages

```
arshen-ac 0.9.6 
atom-beautify 0.33.4 
atom-json-color 0.6.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
file-icons 2.1.36 
git-plus 8.7.1 
highlight-selected 0.16.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
remote-ftp 2.2.2 
seti-syntax 1.2.0 
tool-bar 1.2.0 
```

**Comment by ghost** [comment]
Well, my first for all this. So I'm not sure exactly what I am doing. Thanks.
